---
# This playbook provisions and configures the localhost with ansible-pull.
- hosts: localhost
  become: true
  pre_tasks:
    - name: Update package cache (debian, etc)
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        update_cache: true

- hosts: spice_guest_tools
  roles:
    - spice_guest_tools
